import mysql.connector
import matplotlib.pyplot as plt
import pyfiglet as pf
from termcolor import colored
from tabulate import tabulate
#using the database
mydb = mysql.connector.connect(host="localhost", user = "root", password = "abhi")
mycursor=mydb.cursor()
mycursor.execute("use bank")
#creating required tables
mycursor.execute("create table if not exists Accounts_list(Acc_no int(6) primary key, Acc_holder_name varchar(30) not null, Address varchar(50), City varchar(20), Ph_no varchar(20) unique, Amount int(9))")
mycursor.execute("create table if not exists Transactions(Acc_no int(6), amount int(6), date_of_transaction date, transaction_type char(15), foreign key(Acc_no) references Accounts_list(Acc_no))")
mydb.commit()


#adding default data if not exists

#mycursor.execute("insert into Accounts_list(acc_no, acc_holder_name, address, city, ph_no, amount) values(568925, 'Aayushi Gupta', 'Pebel City', Delhi', 9568645860, 650000)")
#mycursor.execute("insert into Accounts_list(acc_no, acc_holder_name, address, city, ph_no, amount) values(456925, 'Abhigna', 'Flat.no-568, CS Colony', 'Hyderabad', 7989568590, 500000)")
#mycursor.execute("insert into Accounts_list(acc_no, acc_holder_name, address, city, ph_no, amount) values(458965, 'Yash Malhotra', 'Bandra', 'Mumbai', 7895647220, 950000)")
#mycursor.execute("insert into Accounts_list(acc_no, acc_holder_name, address, city, ph_no, amount) values(256745, 'Aman Kumar', 'Plot-12, Suncity', 'Hyderabad', 7898567490, 575000)")
#mycursor.execute("insert into Accounts_list(acc_no, acc_holder_name, address, city, ph_no, amount) values(298756, 'Ansh Mishra', 'KKR Colony', 'Kolkata', 8562145670, 450000)")
#mydb.commit()

#Main Menu
print ()
print ()
result = pf.figlet_format("Welcome to A Cube Bank")
thanks = pf.figlet_format("Thank  you  for  choosing A  Cube  Bank")
print (colored(result, 'cyan'))
print ()
print ()
print (colored("MAIN MENU", 'green').center(140))
print ()
print ()
print (colored("1. Create an Account", 'yellow').center(140))
print ()
print (colored("2. Login to existing Account", 'yellow').center(140))
print ()
print (colored("3. Exit", 'yellow').center(140))
print ()
a = int(input(colored("Enter your Choice : ", 'magenta')))
print()
print()

#Creating New Account
if(a==1):
    print ("**All the fields are mandatory**".center(50))
    name = str(input(colored("Enter your Full Name (maximum 30 characters) : ", 'magenta')))
    add = input(colored("Enter your Address : ", 'magenta'))
    city = str(input(colored("Enter the City : ", 'magenta')))
    mn = input(colored("Enter Mobile No. : ", 'magenta'))
    balance = 0
    accno = mn[3:9]
    mycursor.execute("insert into Accounts_list values('"+accno+"', '"+name+"', '"+add+"', '"+city+"', '"+mn+"', 0)")
    mydb.commit()
    print (colored("Your Account has been successfully created.", 'cyan').center(140))
    print ()
    print (colored("Your Account No. is : ", 'cyan'), accno)
    print()
    print()
    print(colored("MAIN MENU", 'green').center(140))
    print()
    print()
    print(colored("1. Create an Account", 'yellow').center(140))
    print()
    print(colored("2. Login to existing Account", 'yellow').center(140))
    print()
    print(colored("3. Exit", 'yellow').center(140))
    print()
    a = int(input(colored("Enter your Choice : ", 'magenta')))
    print()
    print()

#logging to an existing account
if(a==2):
    b = input(colored("Enter Account Number : ", 'magenta'))
    print()
    print()
    mycursor.execute("select Acc_no from accounts_list")
    o = mycursor.fetchall()
    c = list(o)
    if b not in c == True:
        print ("Invalid Account Number. Please Try Again. ")
    else:
        mycursor.execute("select Acc_holder_name from accounts_list where acc_no = "+b+"") 
        f = mycursor.fetchone()
        for row in f:
            print ("Hello ", "".join(row), "!!!")
        print()
        mycursor.execute("Select amount from accounts_list where acc_no = "+b+"")
        j = mycursor.fetchone()
        y = "".join(str(x) for x in j)
        h = int(y)
    #Menu
        print (colored("Menu", 'green').center(140))
        print()
        print()
        print (colored("1. Deposit Money", 'yellow').center(140))
        print()
        print (colored("2. Withdraw Money", 'yellow').center(140))
        print()
        print (colored("3. Transfer Money to an existing account", 'yellow').center(140))
        print()
        print (colored("4. Account statement and balance", 'yellow').center(140))
        print()
        print (colored("5. Exit", 'yellow').center(140))
        print()
        ch = int(input(colored("Enter your choice : ", 'magenta')))

    #updating the details after depositing the money
        if (ch==1):
            am = int(input("Amount to be Deposited (in numbers only) : "))
            date = input("Enter the date of Transcation (YYYY-MM-DD) : ")
            t="Deposit"
            mycursor.execute("insert into transactions(Acc_no, amount, date_of_transaction, transaction_type) values('"+b+"', '"+str(am)+"', '"+date+"', '"+t+"')")
            mycursor.execute("update Accounts_list set Amount=Amount+'"+str(am)+"' where Acc_no='"+b+"'")
            mydb.commit()
            print ("Your balance has been successfully updated.")
            mycursor.execute("select amount from accounts_list where acc_no = '"+b+"'")
            d = mycursor.fetchone()
            for row in d:
                print ("Your current balance is : ", row)
            print ()
            print ()
            print(colored("Menu", 'green').center(140))
            print()
            print()
            print(colored("1. Deposit Money", 'yellow').center(140))
            print()
            print(colored("2. Withdraw Money", 'yellow').center(140))
            print()
            print(colored("3. Transfer Money to an existing account", 'yellow').center(140))
            print()
            print(colored("4. Account statement and balance", 'yellow').center(140))
            print()
            print(colored("5. Exit", 'yellow').center(140))
            print()
            ch = int(input(colored("Enter your choice : ", 'magenta')))
    #withdrawing the money
        if (ch==2):
            m = int(input("Amount to be withdrawn (in numbers only) : "))
            dat = input("Enter the date of Transcation (YYYY-MM-DD) : ")
            g = "Withdrawal"
            if (m>h):
                print ("Insufficient Balance")
                print ()
                print ()
                print(colored("Menu", 'green').center(140))
                print()
                print()
                print(colored("1. Deposit Money", 'yellow').center(140))
                print()
                print(colored("2. Withdraw Money", 'yellow').center(140))
                print()
                print(colored("3. Transfer Money to an existing account", 'yellow').center(140))
                print()
                print(colored("4. Account statement and balance", 'yellow').center(140))
                print()
                print(colored("5. Exit", 'yellow').center(140))
                print()
                ch = int(input(colored("Enter your choice : ", 'magenta')))
                print()
                print()
            else:
                mycursor.execute("insert into transactions(Acc_no, amount, date_of_transaction, transaction_type) values('"+b+"', '"+str(m)+"', '"+dat+"', '"+g+"')")
                mycursor.execute("update Accounts_list set Amount=Amount-'"+str(m)+"' where Acc_no='"+b+"'")
                mydb.commit()
                print ("Your balance has been successfully updated.")
                mycursor.execute("select amount from accounts_list where acc_no = '"+b+"'")
                p = mycursor.fetchone()
                for row in p:
                    print ("Your current balance is : ", row)
                print ()
                print ()
                print ()
                print(colored("Menu", 'green').center(140))
                print()
                print()
                print(colored("1. Deposit Money", 'yellow').center(140))
                print()
                print(colored("2. Withdraw Money", 'yellow').center(140))
                print()
                print(colored("3. Transfer Money to an existing account", 'yellow').center(140))
                print()
                print(colored("4. Account statement and balance", 'yellow').center(140))
                print()
                print(colored("5. Exit", 'yellow').center(140))
                print()
                ch = int(input(colored("Enter your choice : ", 'magenta')))
                print ()
                print ()
    #transferring money to another existing account

        if (ch==3):
            a1 = input("Enter the account no. of the Beneficiary : ")
            mon = int(input("Enter the amount (in numbers only) : "))
            date2 =input("Enter the date of the transaction : ")
            v = "Debit"
            z = "Credit"
            if (mon>h):
                print ("Insufficient Balance".center(140))
                print ()
                print ()
                print(colored("Menu", 'green').center(140))
                print()
                print()
                print(colored("1. Deposit Money", 'yellow').center(140))
                print()
                print(colored("2. Withdraw Money", 'yellow').center(140))
                print()
                print(colored("3. Transfer Money to an existing account", 'yellow').center(140))
                print()
                print(colored("4. Account statement and balance", 'yellow').center(140))
                print()
                print(colored("5. Exit", 'yellow').center(140))
                print()
                ch = int(input(colored("Enter your choice : ", 'magenta')))
                print()
                print()
            else:
                mycursor.execute("insert into transactions(Acc_no, amount, date_of_transaction, transaction_type) values('"+a1+"', '"+str(mon)+"', '"+date2+"', '"+z+"')")
                mycursor.execute("insert into transactions(Acc_no, amount, date_of_transaction, transaction_type) values('"+b+"', '"+str(mon)+"', '"+date2+"', '"+v+"')")
                mycursor.execute("update Accounts_list set Amount=Amount-'"+str(mon)+"' where Acc_no='"+b+"'")
                mycursor.execute("update Accounts_list set Amount=Amount+'"+str(mon)+"' where Acc_no='"+a1+"'")
                mydb.commit()
                print ("Your balance has been updated")
                print ()
                print ()
                mycursor.execute("select amount from accounts_list where acc_no = '"+b+"'")
                q = mycursor.fetchone()
                for row in q:
                    print ("Your current balance is : ", row)
                print ()
                print ()
                print(colored("Menu", 'green').center(140))
                print()
                print()
                print(colored("1. Deposit Money", 'yellow').center(140))
                print()
                print(colored("2. Withdraw Money", 'yellow').center(140))
                print()
                print(colored("3. Transfer Money to an existing account", 'yellow').center(140))
                print()
                print(colored("4. Account statement and balance", 'yellow').center(140))
                print()
                print(colored("5. Exit", 'yellow').center(140))
                print()
                ch = int(input(colored("Enter your choice : ", 'magenta')))
                print()
                print()
                print()
    #account statement
        if (ch==4):
            mycursor.execute("select date_of_transaction, transaction_type, amount from transactions where acc_no='"+b+"'")
            n = mycursor.fetchall()
            print(tabulate(n, headers=[ "Date of transaction", "Transaction Type", "Amount",], tablefmt= "psql"))
            #count = mycursor.rowcount
            #for row in n:
                #print(row)

            mycursor.execute("select amount from accounts_list where acc_no = '" + b + "'")
            k = mycursor.fetchone()
            for row in k:
                print("Your current balance is : ", row)
                print()
                print()
            mycursor.execute("select sum(amount) from transactions where acc_no = '"+b+"' group by transaction_type")
            ab = mycursor.fetchall()
            hk = [item[0] for item in ab]
            pl = ["Credit", "Debit", "Deposit", "Withdrawal"]

            fig = plt.figure(figsize=(10, 7))
            plt.pie(hk, labels=pl)
            plt.show()

            print(colored("Menu", 'green').center(140))
            print()
            print()
            print(colored("1. Deposit Money", 'yellow').center(140))
            print()
            print(colored("2. Withdraw Money", 'yellow').center(140))
            print()
            print(colored("3. Transfer Money to an existing account", 'yellow').center(140))
            print()
            print(colored("4. Account statement and balance", 'yellow').center(140))
            print()
            print(colored("5. Exit", 'yellow').center(140))
            print()
            ch = int(input(colored("Enter your choice : ", 'magenta')))
            print()
            print()


        if (ch==5):
            print (colored(thanks, 'yellow').center(140))
if (a==3):
    print (colored(thanks, 'yellow').center(140))
mydb.close()